### ISSUE TITLE
The game never finds the biome frozen taiga

### ISSUE THREAD

**Issue by iwanttocompilebutidk** [BluePsychoRanger/SkyBlock_Collection#2]

**Comment by BluePsychoRanger** [comment]
Have you downloaded the latest version for both worldgen and the one block island? What messages did you see in chat?

**Comment by iwanttocompilebutidk** [comment]
it said: "unable to locate frozen taiga, island not generated", any ideas?

**Comment by BluePsychoRanger** [comment]
If that happens, it means there's either no nearby snowy taiga or the calculations failed. You can either run `/locate snowy_taiga` yourself or try creating a new world with a new seed

**Comment by iwanttocompilebutidk** [comment]
okay yeah it was temporary it worked after 15-tries thanks

**Comment by BluePsychoRanger** [comment]
Some improvements have been made to the search algorithm (but it can still fail if the seed doesn't have a snowy taiga biome within ~2k blocks)
