### ISSUE TITLE
Structures don't generate as described (Using latest fabric mod release)

### ISSUE THREAD

**Issue by TheStrefo** [BluePsychoRanger/SkyBlock_Collection#22]
![image_2024-08-02_105308580](https://github.com/user-attachments/assets/9d73067a-4c0a-4d5a-96cb-92032b901220)
![image_2024-08-02_105401654](https://github.com/user-attachments/assets/23129f3a-43cc-4a84-8c66-af1e244fabd3)

As shown in the two images, structures are not generating as described on the Modrinth page. The first image is of the "Stronghold"; It's really just the portal frame. The second image is of a "Trial Chamber". Both structures are evidently supported by the mod, but neither of them are actually generating.

**Comment by BluePsychoRanger** [comment]
I think there is a misunderstanding. Those are working as intended. As stated on the Modrinth page, strongholds will only generate the portal and trial chambers will only generate the bounding box. I can clarify that by "will generate with the same bounding box" means _only_ the bounding box and not the blocks.

**Comment by BluePsychoRanger** [comment]
If you want structures you might wanna look into [Skyblock Infinite](https://modrinth.com/datapack/skyblock-infinite) or wait for the upcoming skyblock structure pack.

**Comment by TheStrefo** [comment]
"I can clarify that by "will generate with the same bounding box" means only the bounding box and not the blocks." Specify that in the description or refrain from including functioning structure generation in the description of the mod.

**Comment by BluePsychoRanger** [comment]
Updated all of the descriptions to clarify that only bounding boxes generate and not blocks.
