### ISSUE TITLE
Everytime opening this world, Minecraft warns: "experimantal settings not supported

### ISSUE THREAD

**Issue by michal-gora** [BluePsychoRanger/SkyBlock_Collection#23]
Everytime opening this world, Minecraft warns: "experimantal settings not supported, see image for more details:
![image](https://github.com/user-attachments/assets/30d14fff-29d6-42de-83bc-c78ea8ae88ae)

**Comment by BluePsychoRanger** [comment]
That warning is a result of the custom world generation settings being marked as experimental by Mojang. It can only be fixed by using a mod called Disable Custom Worlds Advice (or something similar).
https://modrinth.com/mod/dcwa
