### ISSUE TITLE
Suggestion: Add Nether Bedrock Addon for skyvoid_worldgen_structures

### ISSUE THREAD

**Issue by dandud100** [BluePsychoRanger/SkyBlock_Collection#26]
Maybe you should create a addon to allow generating the Bedrock Ceiling and Floor in the Nether so Ghasts can Spawn.

**Comment by BluePsychoRanger** [comment]
What do you mean by this? Ghasts can spawn regardless of the bedrock ceiling.

**Comment by dandud100** [comment]
Oh, maybe they can only spawn on, then that is the reason why they started to spawn in my test. My bad.
