### ISSUE TITLE
Zombies not spawning with shovels

### ISSUE THREAD

**Issue by iwanttocompilebutidk** [BluePsychoRanger/SkyBlock_Collection#3]
While using the starter pack one block, i noticed that only 80% of zombies spawned manually with eggs or commands spawn with shovels. But when they spawn naturally, the odds seem to be the same as vanilla minecraft.

**Comment by BluePsychoRanger** [comment]
There's no way for a datapack to differentiate between a mob spawned naturally and one spawned by an egg or commands, so I'm not sure how that'd happen.

**Comment by iwanttocompilebutidk** [comment]
Idk mb im very unlucky ig
