### ISSUE TITLE
Mobs Arent Spawning

### ISSUE THREAD

**Issue by TheBeholder42** [BluePsychoRanger/SkyBlock_Collection#4]
Ive been using the Starting help and been at it for over an hour and have jumped hundreds of times, ive tried both hard and normal difficulty and have even turned the game rule for mobspawning on. am i missing something or just really unlucky?

**Comment by BluePsychoRanger** [comment]
Assuming you've downloaded version 1.0.0, it it almost definitely luck. Make sure to wait until you stop falling and see the smoke particles before pressing the respawn button as that's part of the time that mobs can spawn. It was found that it takes an average of 400 jumps for a single mob, so the rates are still pretty low even with the buff.

**Comment by TheBeholder42** [comment]
Thanks Mate, i was comparing it to pinu's youtube video and they got a mob in 18 jumps. good to know that was really quick

i summoned a zombie since i thought it might have been broken and i found that after you get the shovel the spawn chances of a shovel go back to quite low. just want to confirm that thats not a bug, makes sense if thats how its supposed to work

**Comment by BluePsychoRanger** [comment]
Yeah, once you get your first shovel the rates return to normal and it starts up the second phase of snowing until you've placed 24 snow blocks.

**Comment by TheBeholder42** [comment]
you should start a subreddit or something so people can talk about rates and strategy outside of the issues page
